openapi: 3.0.0
info:
  title: Audiophile-Ecommerce
  description: Audiophile Ecommerce API
  version: 0.1.9

servers:
  - url: http://localhost:3000/api
    description: local server
  - url: https://audiophile-ecommerce-tunt.onrender.com/api
    description: render server
  - url: https://curious-pear-anemone.cyclic.app/api
    description: cyclic server
paths:
  /products:
    get:
      tags:
        - Products
      responses:
        "200":
          description: Successfully fetched
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /auth/signup:
    post:
      tags:
        - Authorisation
      requestBody:
        description: Create new user
        required: true
        content:
          multipart/form-data:
            schema:
              type: "object"
              properties:
                email:
                  type: string
                password:
                  type: string
                avatar:
                  type: string
                  format: binary
      responses:
        "201":
          description: new user create successfully
  /user/login:
    post:
      tags:
        - Login
      requestBody:
        description: user authorization
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: login successfully
  /user:
    get:
      summary: Get user information
      description: Get information about the authenticated user
      tags:
        - User
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: The user's ID
                  name:
                    type: string
                    description: The user's name
        "401":
          description: Unauthorized
    security:
      - bearerAuth: []
    components:
      securitySchemes:
        bearerAuth:
          type: http
          scheme: bearer
          bearerFormat: JWT
  /cart:
    post:
      tags:
        - cart
      requestBody:
        description: add cart details
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                name:
                  type: string
                number:
                  type: number
                price:
                  type: string
                image:
                  type: string
                userId:
                  type: string
      responses:
        "200":
          description: Cart detail added successfully
  /carts/{userId}:
    get:
      tags:
        - Carts
      parameters:
        - name: userId
          in: path
          required: true
          description: ID of the user's cart to retrieve
          schema:
            type: string
      responses:
        "200":
          description: get the user's cart info successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/CartItem"
  /deleteCarts/{id}:
    delete:
      tags:
        - Carts
      responses:
        "200":
          description: cart deleted
