openapi: 3.0.0
info:
  title: Audiophile-Ecommerce
  description: Audiophile Ecommerce API
  version: 0.1.9

servers:
  - url: http://localhost:3000/api
    description: local server
  - url: https://audiophile-ecommerce-tunt.onrender.com/api
    description: render server
paths:
  /products:
    get:
      tags:
        - Products
      responses:
        "200":
          description: Successfully fetched
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /auth/signup:
    post:
      tags:
        - Authorisation
      requestBody:
        description: Create new user
        required: true
        content:
          multipart/form-data:
            schema:
              type: "object"
              properties:
                email:
                  type: string
                password:
                  type: string
                avatar:
                  type: string
                  format: binary
      responses:
        "201":
          description: new user create successfully
  /user/login:
    post:
      tags:
        - Login
      requestBody:
        description: user authorization
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: login successfully
  /user:
    get:
      summary: Authenticate user
      description: Authenticate a user by verifying their JWT token
      tags:
        - User
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  email:
                    type: string
                    description: The user's email
                  avatar:
                    type: string
                    description: URL of the user's avatar image
        "401":
          description: Access denied. No token provided.
      security:
        - BearerAuth: []
    securitySchemes:
      BearerAuth:
        type: http
        scheme: bearer
        bearerFormat: JWT
  /cart:
    post:
      tags:
        - cart
      requestBody:
        description: add cart details
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                name:
                  type: string
                number:
                  type: number
                price:
                  type: string
                image:
                  type: string
                userId:
                  type: string
      responses:
        "200":
          description: Cart detail added successfully
  /carts:
    get:
      tags:
        - Carts
      responses:
        "200":
          description: get all cart info successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /carts/{id}:
    delete:
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
      tags:
        - Carts
      responses:
        "200":
          description: cart deleted
